Github actions fixes
Installed prerequisites in Github actions runner
Added trx-based test result output
Added "missing SQL server" detection for Test skipping purposes.
Split "Build & Test" from Docker publish
Adjusted badge
Split docker build from publish

diff --git a/.github/workflows/dotnet-core-build-and-test.yml b/.github/workflows/dotnet-core-build-and-test.yml
--- a/.github/workflows/dotnet-core-build-and-test.yml
+++ b/.github/workflows/dotnet-core-build-and-test.yml
@@ -9,26 +9,71 @@ on:
 
 jobs:
   build:
-
+    name: Builds and tests libraries & app
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
     - name: Setup dotnet
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: |
           7.0.x
+          
+    # See also DockerFile
+    - name: Install Ghostscript (for rendering PDFs)
+      run: sudo apt-get install -y ghostscript
+    
+    - name: Install Time Zone data
+      run: sudo apt-get install -y tzdata
+    
+    #- name: Addresses Database Globalization issues
+    #  run: sudo apt-get install -y icu-libs
+      
     - name: Install dependencies
       run: dotnet restore InkyCal.sln
+
     - name: Build
       run: dotnet build InkyCal.sln --configuration Release --no-restore
+
     - name: Test
-      run: dotnet test InkyCal.sln --no-restore --verbosity normal
+      run: dotnet test InkyCal.sln --no-restore --verbosity detailed --logger "trx;LogFileName=test-results.trx"
+
+    - name: 'Upload Artifact'
+      uses: actions/upload-artifact@v3
+      with:
+        name: testresults
+        path: '**/*.trx'
+        retention-days: 1
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+          name: Dotnet testresult # Name of the check run which will be created
+          path: '**/*.trx'        # All test results
+          reporter: dotnet-trx    # Format of test results
+
+  build-docker:
+    name: Build Docker image
+    runs-on: ubuntu-latest
+    steps:
+    - name: Build Docker image
+      # You may pin to the exact commit or the version.
+      # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
+      uses: docker/build-push-action@v4
+      with:
+        push: false
+        tags: atreyu/inkycal.server:latest
+
+  publish:
+    name: Publish to docker.io
+    runs-on: ubuntu-latest
+    needs: [build, build-docker]
+    steps:
     - name: Docker Login
       # You may pin to the exact commit or the version.
-      # uses: docker/login-action@34d5f75b0d6d0d22f06d83acf2fa1b144409ec83
-      uses: docker/login-action@v1.4.1
+      uses: docker/login-action@v2
       with:
         # Server address of Docker registry. If not set then will default to Docker Hub
         # registry: # optional
@@ -38,41 +83,10 @@ jobs:
         password: ${{ secrets.DOCKER_PASSWORD }}
         # Log out from the Docker registry at the end of a job
         # logout: # optional, default is true
-    - name: Build and push Docker images
+
+    - name: Push Docker image
       # You may pin to the exact commit or the version.
-      # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
-      uses: docker/build-push-action@v1.1.1
+      uses: docker/build-push-action@v4
       with:
-        # Username used to log in to a Docker registry. If not set then no login will occur
-        # username: # optional
-        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
-        # password: # optional
-        # Server address of Docker registry. If not set then will default to Docker Hub
-        # registry: # optional
-        # Docker repository to tag the image with
-        repository: 'atreyu/inkycal.server' 
-        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
-        # tags:  # optional
-        # tags: github.ref
-        # Automatically tags the built image with the git reference as per the readme
-        #tag_with_ref: # optional
-        # Automatically tags the built image with the git short SHA as per the readme
-        #tag_with_sha: # optional
-        # Path to the build context
-        # path: # optional, default is .
-        # Path to the Dockerfile (Default is '{path}/Dockerfile')
-        # dockerfile: # optional
-        # Sets the target stage to build
-        # target: # optional
-        # Always attempt to pull a newer version of the image
-        # always_pull: # optional
-        # Comma-delimited list of build-time variables
-        # build_args: # optional
-        # Comma-delimited list of images to consider as cache sources
-        # cache_froms: # optional
-        # Comma-delimited list of labels to add to the built image
-        labels: inky-calender,inkycal
-        # Adds labels with git repository information to the built image
-        add_git_labels: true # optional
-        # Whether to push the image
-        push: true # optional, default is true
+        push: true
+        tags: atreyu/inkycal.server:latest
